before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hunspell

script:
- echo "Hi 1"
- ls -l ./tools/spell-checker
- hunspell -p ./tools/spell-checker/spell-check-recognized-words -l wallets.asciidoc
- echo "Hi 2"

notifications:
  email: false


